### ISSUE TITLE
Add support for EPA AQI adjustment for PM2.5

### ISSUE THREAD

**Issue by squidpickles** [kelnos/aqi-rs#1]
The EPA completed a [study](https://cfpub.epa.gov/si/si_public_record_Report.cfm?dirEntryId=350075&Lab=CEMM) in 2020 that corrects PurpleAir-derived sensor values, bringing them closer to AirNow official measurements.

From this study, it appears that the EPA adjustment outperforms several existing adjustments, including LRAPA.

It does require humidity as an input, but this is available from PurpleAir sensors, so shouldn't be an issue for users of the library.

PR coming that would add this adjustment, in the style of the existing ones. No API fanciness, just an extra argument for humidity.

Thanks for the work you've done on this so far!

**Comment by kelnos** [comment]
I actually wrote this for a non-PurpleAir sensor, so requiring humidity might not work for everyone.  But if the EPA adjustment requires it, then I guess people without humidity measurements just will have to use a different (or no) adjustment ;)

**Comment by squidpickles** [comment]
Yeah, I'm using a similar sensor to PurpleAir (PMS7003), but BME280 for humidity alongside it. Not sure what they've got, but assuming it's relatively accurate, it should match well. At least, anecdotally, the numbers seem to match official for my area.

But yeah, I guess it does make it easy to decide - don't use it if you can't find a way to populate that argument. :)

**Comment by kelnos** [comment]
Right :)

I have a SEN0177, which I don't believe gives humidity (though the code that reads it skips over some data in the payload, so maybe there _is_ humidity in there after all), but I also have a DHT22 connected to the same device, so I can get humidity from that.

**Comment by kelnos** [comment]
Sorry for the delay!  I've been traveling, but just published 0.1.1 with your addition.  Thank you!
